name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: |
          CI=false npm run build
        env:
          API_KEY: ${{ secrets.API_KEY }},
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }},
          DATABASE_URL: ${{ secrets.DATABASE_URL }},
          PROJECT_ID: ${{ secrets.PROJECT_ID }},
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }},
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }},
          APP_ID: ${{ secrets.APP_ID }},
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build